### ISSUE TITLE
apc_num_items in euro?

### ISSUE THREAD

**Issue by zuphilip** [OpenAPC/openapc-olap#7]
I see that the variable `apc_num_items` has the measure `euro`, but this seems wrong.

E.g.

https://github.com/OpenAPC/openapc-olap/blob/0b18a0cab08396b5d7f717b1c465bd0ef2d34650/static/templates/MODEL_FIRST_PART#L22-L27

but also in some other files.

**Comment by cbroschinski** [comment]
In theory, yes, but since this is a "count" function (equivalent to COUNT in SQL), it doesn't really matter. It just counts rows in one of the data columns, and "euro" is as good as any other. I could make this somewhat more explicit by counting something else (DOIs, for example), but then I would have to define another measure first, which would just add more boilerplate code.

But still good to see that someone delves into those really boring OLAP model definitions. :-)

**Comment by zuphilip** [comment]
Ah, I misinterpreted this. I thought that this means that the number of articles will be measured in euros, but you only count how many times this field is present which then is total number of articles. Sorry for the confusion.

Yeah, I was interested in API and played around a little with this OLAP ;-)
